baseURL: "http://example.com"
mongodb:
  connection:
    server: "localhost:27017"
    username: "identibotUser" # Optional; omit if username/password authentication is not used.
    urlExtra: ""
    options: { }
  dbName: "identibot"
petrock:
  clientID: "ABCDEFGHIJK"
mitDeveloperConnection:
  clientID: "0123456789"
discord:
  clientID: "12345678901234567890"
supportContact:
  email: "support@example.com"
commandSettings:
  directory:
    enableAccountLinkStatusInDirectorySearch: true
caching:
  dining: true
singleServerMessages: false
smtp:
  hostname: 'outgoing.example.com'
  port: 465
  username: 'username'
  fromUser: '"MIT IdentiBot" <identibot@example.com>'
  replyTo: 'support@example.com'
