baseURL: "http://example.com"
mongodb:
  connection:
    server: "localhost:27017"
    username: "identibotUser" # Optional; omit if username/password authentication is not used.
    urlExtra: ""
    options: { }
  dbName: "identibot"
petrock:
  clientID: "ABCDEFGHIJK"
discord:
  clientID: "12345678901234567890"
emoji:
  ci_h: "12345678901234567890"
  ci_hw: "12345678901234567890"
  graduate: "12345678901234567890"
  undergraduate: "12345678901234567890"
singleServerMessages: false
